### ISSUE TITLE
Not working on Craft 2.5.2762?

### ISSUE THREAD

**Issue by jameswragg** [lukeholder/craft-dbug#10]
Hi, I really wanted a better way to work with Craft templates & really liked the look of this. Is it still maintained? Installed & outputting a green box but seems empty or broken?

https://www.dropbox.com/s/lzi6ppokxxpyae4/Screenshot%202016-02-16%2016.33.20.png?dl=0

Thanks,
James

**Comment by lukeholder** [comment]
recommend using https://github.com/mildlygeeky/craft_kint

will be closing this project.

**Comment by jameswragg** [comment]
👌
