### ISSUE TITLE
Class 'Ospinto\Debug' not found

### ISSUE THREAD

**Issue by tylerwillingham** [lukeholder/craft-dbug#2]
Using 

```
{{ craft.request | dbug }}
```

at the top of my main wrapper template outputs the following:

```
Fatal error: Class 'Ospinto\Dbug' not found in /Users/XXXXXXX/Development/craft_project_name/craft/plugins/dbug/twigextensions/dbugTwigExtension.php on line 94
```

**Comment by dovrosenberg** [comment]
I'm still getting this error in release 2.5.

**Comment by lukeholder** [comment]
@dovrosenberg you need to download from the releases page here: https://github.com/lukeholder/craft-dbug/releases

The github repo zip file link is the code only and not the compiled release. You need to download a release.
