### ISSUE TITLE
casing causes crashing, but otherwise great

### ISSUE THREAD

**Issue by narration-sd** [lukeholder/craft-dbug#3]
Luke, I put this aside a long time ago, because it gave stack traces when enabled in Craft. This evening there was the moment to take a look, and the problem is easy.  Then I found it's really a nice job, especially with the collapsed outputs, and so I will use it from now on.

As far as the bug, you've simply mis-capitalized in the spelling of TwigExtensions/DbugTwigExtension.php. 

It should be dbugTwigExtension.php, to agree with general conventions and your call to include it in the mainline code.

I just changed the spelling on the site. This matters on Unix; you are probably working on Windows, I guess.

Cheers,
Clive

**Comment by lukeholder** [comment]
This is why github has a releases system.

On Tue, Jun 3, 2014 at 2:29 PM, Luke Holder wrote:

> Narration,
> 
> The github repo does not have the composer dependancies. If you just
> download the repo you need to do a composer install. The release has all
> dependancies.
> 
> On Tue, Jun 3, 2014 at 1:51 PM, narration notifications@github.com
> wrote:
> 
> > Hey, Luke. I wrote you a comment on 2.0 that seems to have been in error.
> > 
> >    -
> > 
> >    if I take this releases/tag/2.0 zip you recommend, indeed I get dbug
> >    with the vendors folder and the casing issue fixed. As well, the deprecated
> >    call is upgraded now, addTwigExtension.
> >    -
> > 
> >    the reason I thought not: if you clone the git, either by pulling the
> >    latest on top of a previous repository, you don't get these things. I don't
> >    quite fathom this, but maybe it's something about how you've chosen to run
> >    your git setup, and it's fine for you.
> > 
> > Anyway, that's why I came back, while things do look fine now from the
> > tag/2.0 release.
> > 
> > Best,
> > Clive
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/lukeholder/craft-dbug/issues/3#issuecomment-44922519
> > .
> 
> ## 
> 
> Luke Holder
> 
> (+61) 0427 428 364

## 

Luke Holder

(+61) 0427 428 364
