### ISSUE TITLE
Plugin breaks Craft plugins page!

### ISSUE THREAD

**Issue by migswd** [lukeholder/craft-dbug#9]
First time I see that, after copying the plugin files in plugins directory it breaks Craft
![screen shot 2015-08-17 at 19 49 52](https://cloud.githubusercontent.com/assets/3531623/9321306/77c0e682-4519-11e5-8643-da5b478270e9.jpg)

**Comment by lukeholder** [comment]
You have downloaded the zip from github source code repo... You need to download from https://github.com/lukeholder/craft-dbug/releases to get the full version with all dependancies.

**Comment by lukeholder** [comment]
I will test on latest craft and make a new release tomorrow.

**Comment by lukeholder** [comment]
recommend now using https://github.com/mildlygeeky/craft_kint

will close this project shortly.
